apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtap-415-e2e
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  description: >-
    This is an integration pipeline to deploy Ephemeral cluster
  params:
    - description: 'Openshift version for epehmeral cluster deployment'
      name: ocp-version
      default: '4.15.9'
      type: string
  tasks:
    - name: check-label
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/usr/bin/env python3
        import json
        labels=json.loads("""{{ body.pull_request.labels }}""")
        for label in labels:
            if label['name'] == 'bug':
              print('This is a PR targeting a BUG')
              exit(0)
        print('This is not a PR targeting a BUG :(')
        exit(1) 