apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-world-pipeline-run
spec:
  pipelineSpec:
    tasks:
      - name: hello-world-task
        taskRef:
          name: hello-world-task
  tasks:
    - name: hello-world-task
      taskSpec:
        steps:
          - name: hello-world-step
            image: alpine
            script:
              - echo "Hello, World!"
