apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtap-415-e2e
spec:
  description: >-
    This is an integration pipeline to deploy Ephemeral cluster
  params:
    - description: 'Test ID corresponding to a defined Konflux integration test'
      name: test-id
      default: ''
    - description: 'Test name corresponding to a defined Konflux integration test'
      name: test-name
      default: ''
    - description: 'Openshift version for epehmeral cluster deployment'
      name: ocp-version
      default: '4.15.9'
      type: string
  tasks:
    - name: deploy-ocp-task
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/rhtap-e2e
          - name: revision
            value: integration-test
          - name: pathInRepo
            value: integration/task.yaml
      params:
        - name: test-id
          value: $(context.pipelineRun.uid)
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-version
          value: $(params.ocp-version)
