apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-tekton
spec:
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - name: say-hello
            image: alpine
            script: |
              echo "Hello, Tekton!"
