apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtap-415-e2e
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  description: >-
    This is an integration pipeline to deploy Ephemeral cluster
  params:
    - description: 'Openshift version for epehmeral cluster deployment'
      name: ocp-version
      default: '4.15.9'
      type: string
    - description: 'Openshift version for epehmeral cluster deployment'
      name: event-type
      default: $(annotations.pac.test.appstudio.openshift.io/event-type)
      type: string
  tasks:
    - name: deploy-ocp-task
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/rhtap-e2e
          - name: revision
            value: integration-test
          - name: pathInRepo
            value: integration/task.yaml
      params:
        - name: ocp-version
          value: $(params.ocp-version)
        - name: event-type
          value:  $(params.event-type)
