apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-param-enum
spec:
  params:
    - name: message
      description: "Message to be printed"
      type: string
      default:
        secretKeyRef:
          name: fake-test
          key: fake-secret
  tasks:
    - name: task1
      params:
        - name: message
          value: $(params.message)
      taskRef:
        name: hello-world-task
        resolver:
          git:
            url: https://github.com/konflux-ci/integration-examples
            revision: integration-test
            file: integration/task.yaml
