apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-param-enum
spec:
  params:
  - name: message
    default: "hello world"
  tasks:
  - name: task1
    params:
      - name: message
        value: $(params.message)
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/konflux-ci/integration-examples
        - name: revision
          value: integration-test
        - name: pathInRepo
          value: integration/task.yaml
