apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-world-task
spec:
  params:
    - name: message
      type: string
  steps:
    - name: hello
      image: quay.io/redhat-appstudio/appstudio-utils:25c43952f247797d8de4cf16e668b954292e8794
      script: |
        #!/bin/bash
        echo "$(params.message)"
