apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
    - name: event-type
      type: string
  steps:
    - name: check-label
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/sh
        if [ -n "$TEKTON_EVENT_TYPE" ] && [ "$TEKTON_EVENT_TYPE" == "pull_request" ]; then
          echo "pull_request"
        else
          echo "push"
        fi
      env:
        - name: TEKTON_EVENT_TYPE
          value: $(TEKTON_EVENT_TYPE)
