apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request"
spec:
  params:
    - name: ocp-version
      type: string
  steps:
    - name: hello
      image: quay.io/redhat-appstudio/appstudio-utils:25c43952f247797d8de4cf16e668b954292e8794
      script: |
        #!/bin/bash
        echo "Task Annotations:"
        cd /workspace

        oc version
        oc whoami
