apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
    - name: event-type
      default: pac.event_type
      type: string
  steps:
    - name: check-label
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        echo $(params.event-type)
