apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
    - name: event-type
      type: string

  steps:
    - name: check-pull-request
      image: alpine:latest
      env:
        - name: TEST_ID
          value: $(context.pipelineRun.uid)
        - name: TEST_NAME
          value: $(context.pipelineRun.name)
      script: |
        #!/bin/sh
        echo ${TEST_ID}
        echo ${TEST_NAME}
        if [ -n "$TEKTON_PULL_PULL_REF" ]; then
          echo "Running from pull request"
        else
          echo "Not running from pull request"
        fi
    - name: hello
      image: quay.io/redhat-appstudio/appstudio-utils:25c43952f247797d8de4cf16e668b954292e8794
      script: |
        #!/bin/bash
        echo "Task Annotations:"
        echo ${ENV_VARIABLE_NAME}
        cd /workspace
        echo $(params.event-type)
        oc version
        oc whoami