apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
    - name: event-type
      type: string
    - name: AWS_ACCESS_KEY_ID
      description: "AWS access key ID"
    - name: AWS_SECRET_ACCESS_KEY
      description: "AWS secret access key"
  steps:
    - name: check-pull-request
      image: alpine:latest
      script: |
        #!/bin/sh
        echo $(params.AWS_ACCESS_KEY_ID)

    - name: hello
      image: quay.io/redhat-appstudio/appstudio-utils:25c43952f247797d8de4cf16e668b954292e8794
      script: |
        #!/bin/bash
        echo "Task Annotations:"
        echo ${ENV_VARIABLE_NAME}
        cd /workspace
        echo $(params.event-type)
        oc version
        oc whoami