apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
    - name: event-type
      type: string
  steps:
    - name: hello
      image: quay.io/redhat-appstudio/appstudio-utils:25c43952f247797d8de4cf16e668b954292e8794
      script: |
        #!/bin/bash
        echo "$(params.ocp-version)"
        echo "$(params.event-type)"
        oc version
        oc whoami

        for param in $(params); do
          echo "$param: $(params.$param)"
        done