apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: test-id
      type: string
    - name: test-name
      type: string
    - name: ocp-version
      type: string
  steps:
    - name: check-pull-request
      image: alpine:latest
      env:
        - name: TEST_ID
          value: $(params.test-id)
        - name: TEST_NAME
          value: $(params.test-name)
      script: |
        #!/bin/sh
        cd /workspace
        mkdir -p test
        ls -larth
        echo ${TEST_ID}
        echo ${TEST_NAME}
    - name: check-pull-requests
      image: alpine:latest
      env:
        - name: TEST_ID
          value: $(params.test-id)
        - name: TEST_NAME
          value: $(params.test-name)
      script: |
        #!/bin/sh
        cd /workspace
        ls -larth
