apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-ocp
spec:
  params:
    - name: ocp-version
      type: string
  steps:
  - name: bash
    image: registry.access.redhat.com/ubi9/ubi
    script: |
      if {{ body.pull_request.state == "open" }}; then
        echo "PR is Open"
      fi