apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-app
spec:
  description: >-
    Expects an Snapshot deployed.
  steps:
    - image: quay.io/redhat-appstudio/hacbs-test:latest
      env:
        - name: SNAPSHOT
          value: "test-snap"
        - name: NAMESPACE
          value: "test-ns"
      script: |
        echo -e "${SNAPSHOT}"
        echo -e "${NAMESPACE}"